# Generated by Django 5.0.2 on 2024-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.CharField(default='static/images/profile_3.jpg', max_length=255),
        ),
    ]
