# Generated by Django 5.0.2 on 2024-05-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ImageField(default='static/images/profile_3.jpg', upload_to=''),
        ),
    ]
