# Generated by Django 5.0.2 on 2024-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ImageField(default='static/images/profile_1.jpg', upload_to=''),
        ),
    ]
