# Generated by Django 5.0.2 on 2024-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ImageField(default='media/3a081e38-cb17-487e-b885-bb7bf79b4a89.jpg', upload_to='profiles'),
        ),
    ]
