# Generated by Django 5.0.2 on 2024-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_home_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(default='logo.png', upload_to='logo')),
                ('footer_caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class_1', models.CharField(max_length=50)),
                ('icon_class_2', models.CharField(max_length=50)),
            ],
        ),
    ]
