# Generated by Django 5.0.2 on 2024-05-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_copyright_footer_footer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_link',
            name='link',
            field=models.TextField(default='www.google.com'),
        ),
    ]
