# Generated by Django 5.0.2 on 2024-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_footer_link_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('info', models.TextField(default='kavappura')),
                ('icon_class_1', models.CharField(max_length=50)),
                ('icon_class_2', models.CharField(max_length=50)),
            ],
        ),
    ]
